service: file-upload-api #Name of your App

provider:
 name: aws
 runtime: nodejs14.x # Node JS version
 memorySize: 128
 timeout: 15
 stage: production
 region: eu-west-1 # AWS region
 profile: personal

functions:
 api:
   handler: lambda.handler
   events: 
      - http: 
          path: /
          method: ANY
          cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true